name: Bug report
description: Report something that is broken or behaving unexpectedly in RootStream
title: "[BUG] "
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug in **RootStream**.  
        Please fill in as much detail as you can — especially your distro, kernel, GPU and drivers.

  - type: input
    id: version
    attributes:
      label: RootStream version or commit hash
      description: >
        The version you are running (e.g. v0.1.0 or the output of `git rev-parse HEAD`).
      placeholder: v0.1.0
    validations:
      required: true

  - type: input
    id: distro
    attributes:
      label: Distribution and version
      description: >
        Your Linux distribution and version.
      placeholder: Arch Linux (up to date) / Ubuntu 24.04 / Fedora 41
    validations:
      required: true

  - type: input
    id: kernel
    attributes:
      label: Kernel version
      description: Output of `uname -r`.
      placeholder: 6.7.1-arch1-1
    validations:
      required: false

  - type: input
    id: gpu
    attributes:
      label: GPU and driver
      description: >
        Include vendor, model and driver stack (e.g. "AMD RX 6800 (mesa 24.x)", "NVIDIA RTX 4070 (535.xx)", "Intel Arc (mesa 24.x)").
      placeholder: NVIDIA RTX 4070 (535.xx)
    validations:
      required: true

  - type: dropdown
    id: gpu_vendor
    attributes:
      label: GPU vendor
      description: Select the main GPU used for RootStream.
      options:
        - AMD
        - NVIDIA
        - Intel
        - Other / mixed
    validations:
      required: false

  - type: dropdown
    id: session_type
    attributes:
      label: Session type
      description: >
        Which desktop/session type are you using?
      options:
        - Wayland
        - X11
        - TTY / no DE
        - Unknown / Other
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: >
        A clear and concise description of what the bug is.
      placeholder: >
        When I start RootStream with ..., the client shows ..., but I expected ...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: >
        Step-by-step instructions so we can reproduce the issue.
      placeholder: |
        1. Run `rootstream --service --verbose`
        2. Scan QR from client ...
        3. Start streaming ...
        4. Observe error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: >
        What did you expect to happen?
      placeholder: >
        I expected the stream to start and show my desktop with <60ms latency...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: >
        What actually happened instead?
      placeholder: >
        The client stays on a black screen and the host logs show ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / terminal output
      description: |
        Please run RootStream with verbose logging and paste the relevant output.

        Example:
        ```bash
        rootstream --service --verbose 2>&1 | tee rootstream.log
        ```
      render: bash
      placeholder: |
        [paste logs here]
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or recordings
      description: >
        If applicable, add screenshots or short screen recordings to help explain your problem.
      placeholder: >
        Drag and drop screenshots or link to a short video.
    validations:
      required: false

  - type: textarea
    id: extra_info
    attributes:
      label: Additional context
      description: >
        Any other context, configuration details, or hardware specifics that might be relevant.
      placeholder: >
        e.g. Using custom kernel, unusual network setup, multiple GPUs, running inside VM, etc.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and this bug has not been reported yet.
          required: true
        - label: I have tried with the latest version of RootStream (or `main` branch).
          required: false
        - label: I have run RootStream with `--verbose` and attached relevant logs.
          required: false
