name: Feature request
description: Suggest an idea or improvement for RootStream
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for RootStream.

        RootStream prioritizes **low latency**, **Linux-native design**, and **simplicity**.
        Please explain how your idea fits those goals.

  - type: textarea
    id: problem
    attributes:
      label: Problem / use case
      description: What problem are you trying to solve? Why is it important?
      placeholder: |
        When I try to ..., I run into ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe what you’d like RootStream to do.
      placeholder: |
        I’d like RootStream to support ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you tried other approaches or tools?
      placeholder: |
        I’ve considered ...
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Latency and complexity impact
      description: How might this affect latency, resource usage, or complexity?
      placeholder: |
        This might add some complexity in ..., but ...
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for similar requests.
          required: true
        - label: I believe this feature aligns with RootStream’s low-latency, Linux-native goals.
          required: false
