# Podfile for RootStream iOS
# CocoaPods dependencies for iOS application

platform :ios, '15.0'
use_frameworks!

target 'RootStream' do
  # Audio
  pod 'libopus', '~> 1.3'
  
  # Security
  pod 'TrustKit', '~> 3.0'
  
  # Networking (optional, using native Network framework)
  # pod 'CocoaAsyncSocket'
  
  target 'RootStreamTests' do
    inherit! :search_paths
    # Testing pods
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
